version: '3.8'
services:
    spark-local-dev:
        image: spark-base
        container_name: spark-local-dev
        build: .
        volumes:
            - ./spark-app:/opt/spark/work-dir
        ports:
            - 8888:8888
            - 8080:8080
