version: '3.8'
services:
    spark-local-dev:
        image: spark-base
        container_name: spark-local-dev
        build: .
        volumes:
            - ./spark-app:/opt/spark/work-dir
        ports:
            - 8888:8888
            - 8080:8080

    minio:
        image: docker.io/bitnami/minio:2024
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio-pass
            - MINIO_FORCE_NEW_KEYS=yes
            - MINIO_DEFAULT_BUCKETS=spark-dev-bucket